export enum ICONS {
  ARROW_LEFT = "arrow-left",
  ASCLEPIUS = "asclepius",
  BARBELL = "barbell",
  BASKET = "basket",
  COFFEE = "coffee",
  COOKIE = "cookie",
  FADERS = "faders",
  FORK_KNIFE = "fork-knife",
  GLOBE = "globe",
  MAGNIFYING_GLASS = "magnifying-glass",
  MAP_PIN = "map-pin",
  MEAL = "meal",
  NAVIGATION_ARROW = "navigation-arrow",
  PHONE = "phone",
  SHARE_NETWORK = "share-network",
  LINKEDIN = "linkedin",
  INSTAGRAM = "instagram",
  TIKTOK = "tiktok",
  FACEBOOK = "facebook",
  STOREFRONT = "storefront",
  TAG = "tag",
  X = "x",
  INFINITY_SEARCH = "infinity-search",
}
