export enum ICONS {
  ARROW_LEFT = "arrow-left",
  ASCLEPIUS = "asclepius",
  BARBELL = "barbell",
  BASKET = "basket",
  COFFEE = "coffee",
  COOKIE = "cookie",
  FADERS = "faders",
  FORK_KNIFE = "fork-knife",
  GLOBE = "globe",
  MAGNIFYING_GLASS = "magnifying-glass",
  MAP_PIN = "map-pin",
  MEAL = "meal",
  NAVIGATION_ARROW = "navigation-arrow",
  PHONE = "phone",
  SHARE_NETWORK = "share-network",
  SOCIAL_MEDIA_ICON_1 = "social-media-icon-1",
  SOCIAL_MEDIA_ICON_2 = "social-media-icon-2",
  SOCIAL_MEDIA_ICON_3 = "social-media-icon-3",
  SOCIAL_MEDIA_ICON = "social-media-icon",
  STOREFRONT = "storefront",
  TAG = "tag",
  X = "x",
  INFINITY_SEARCH = "infinity-search",
}
