export const SEARCH_SUGGESTIONS_DEBOUNCE_MS = 300;
export const SEARCH_MAP_DEBOUNCE_MS = 500;
export const SEARCH_SUGGESTION_LIMIT = 10;
export const MAP_SEARCH_MAX_FEATURES = 2500;
export const SEARCH_MAP_MIN_QUERY_LENGTH = 2;
