import { ICONS } from "@/enums";
import { IIconProps } from "@/types";
import { ComponentType, createElement } from "react";
import {
  ArrowElbowDownLeftIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowUpIcon,
  AsclepiusIcon,
  BabyIcon,
  BarbellIcon,
  BasketIcon,
  BedIcon,
  BookOpenTextIcon,
  BriefcaseIcon,
  BuildingsIcon,
  BusIcon,
  CarIcon,
  CoffeeIcon,
  CookieIcon,
  FadersIcon,
  FirstAidKitIcon,
  FlowerLotusIcon,
  ForkKnifeIcon,
  GasPumpIcon,
  GlobeIcon,
  HeartbeatIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MartiniIcon,
  NavigationArrowIcon,
  PaletteIcon,
  PhoneIcon,
  PlanetIcon,
  PopcornIcon,
  ShareNetworkIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  StorefrontIcon,
  TagIcon,
  XIcon,
  type IconProps as PhosphorIconProps,
} from "@phosphor-icons/react";
import { AppIconComponent } from "./icons.types";

const withPhosphorFill = (
  IconComponent: ComponentType<PhosphorIconProps>,
  defaultWeight: PhosphorIconProps["weight"] = "fill",
): AppIconComponent => {
  const WrappedIcon = ({ ...props }: IIconProps) =>
    createElement(IconComponent, {
      ...(props as unknown as PhosphorIconProps),
      weight: (props as { weight?: PhosphorIconProps["weight"] }).weight ?? defaultWeight,
    });
  return WrappedIcon;
};

export const phosphorIconRegistry: Partial<Record<ICONS, AppIconComponent>> = {
  [ICONS.ARROW_LEFT]: withPhosphorFill(ArrowLeftIcon),
  [ICONS.ARROW_UP]: withPhosphorFill(ArrowUpIcon),
  [ICONS.ARROW_DOWN]: withPhosphorFill(ArrowDownIcon),
  [ICONS.ARROW_ELBOW_DOWN_LEFT]: withPhosphorFill(ArrowElbowDownLeftIcon),
  [ICONS.ASCLEPIUS]: withPhosphorFill(AsclepiusIcon),
  [ICONS.BARBELL]: withPhosphorFill(BarbellIcon),
  [ICONS.BASKET]: withPhosphorFill(BasketIcon),
  [ICONS.BED]: withPhosphorFill(BedIcon),
  [ICONS.BOOK_OPEN_TEXT]: withPhosphorFill(BookOpenTextIcon),
  [ICONS.BRIEFCASE]: withPhosphorFill(BriefcaseIcon),
  [ICONS.BUILDINGS]: withPhosphorFill(BuildingsIcon),
  [ICONS.BUS]: withPhosphorFill(BusIcon),
  [ICONS.CAR]: withPhosphorFill(CarIcon),
  [ICONS.CHILDCARE]: withPhosphorFill(BabyIcon),
  [ICONS.COFFEE]: withPhosphorFill(CoffeeIcon),
  [ICONS.COOKIE]: withPhosphorFill(CookieIcon),
  [ICONS.FADERS]: withPhosphorFill(FadersIcon),
  [ICONS.FIRST_AID_KIT]: withPhosphorFill(FirstAidKitIcon),
  [ICONS.FLOWER_LOTUS]: withPhosphorFill(FlowerLotusIcon),
  [ICONS.FORK_KNIFE]: withPhosphorFill(ForkKnifeIcon),
  [ICONS.GAS_PUMP]: withPhosphorFill(GasPumpIcon),
  [ICONS.GLOBE]: withPhosphorFill(GlobeIcon),
  [ICONS.HEARTBEAT]: withPhosphorFill(HeartbeatIcon),
  [ICONS.MAGNIFYING_GLASS]: withPhosphorFill(MagnifyingGlassIcon),
  [ICONS.MAP_PIN]: withPhosphorFill(MapPinIcon),
  [ICONS.MARTINI]: withPhosphorFill(MartiniIcon),
  [ICONS.NAVIGATION_ARROW]: withPhosphorFill(NavigationArrowIcon),
  [ICONS.PALETTE]: withPhosphorFill(PaletteIcon),
  [ICONS.PHONE]: withPhosphorFill(PhoneIcon),
  [ICONS.PLANET]: withPhosphorFill(PlanetIcon),
  [ICONS.POPCORN]: withPhosphorFill(PopcornIcon),
  [ICONS.SHARE_NETWORK]: withPhosphorFill(ShareNetworkIcon),
  [ICONS.SHIELD_CHECK]: withPhosphorFill(ShieldCheckIcon),
  [ICONS.SHOPPING_BAG]: withPhosphorFill(ShoppingBagIcon),
  [ICONS.STOREFRONT]: withPhosphorFill(StorefrontIcon),
  [ICONS.TAG]: withPhosphorFill(TagIcon),
  [ICONS.X]: withPhosphorFill(XIcon, "bold"),
};
