export enum ICONS {
  ARROW_UP = "arrow-up",
  ARROW_DOWN = "arrow-down",
  ARROW_ELBOW_DOWN_LEFT = "arrow-elbow-down-left",
  BOOK_OPEN_TEXT = "book-open-text",
  BUILDINGS = "buildings",
  FADERS = "faders",
  MAGNIFYING_GLASS = "magnifying-glass",
  MAP_PIN = "map-pin",
  PALETTE = "palette",
  SHARE_NETWORK = "share-network",
  SHIELD_CHECK = "shield-check",
  SHOPPING_BAG = "shopping-bag",
  STOREFRONT = "storefront",
  TAG = "tag",
  X = "x",
}
